# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nadrama < Formula
  desc "The official CLI for Nadrama.com"
  homepage "https://nadrama.com"
  version "20250404133712"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nadrama-com/nadrama/releases/download/20250404133712/nadrama_darwin_x86_64.tar.gz"
      sha256 "4833feda900c55c8a5d9813e5a4970e145ee8af1851e20333532d0e6779ada7e"

      def install
        bin.install "nadrama"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nadrama-com/nadrama/releases/download/20250404133712/nadrama_darwin_arm64.tar.gz"
      sha256 "827c2b458b583e2dde9ab1d5112060a1bdad3d4428097b61589cf8d2f919f231"

      def install
        bin.install "nadrama"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nadrama-com/nadrama/releases/download/20250404133712/nadrama_linux_x86_64.tar.gz"
        sha256 "07b8a5699daf2bb834a1d17d44f8cef4d50cf4ea9cd97310a0b71401b7d1d603"

        def install
          bin.install "nadrama"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nadrama-com/nadrama/releases/download/20250404133712/nadrama_linux_arm64.tar.gz"
        sha256 "2e0ce755e789b605f7cabeb4dbfaa7b3af2f9f0b41285f57ef7f8ef61b8d02fc"

        def install
          bin.install "nadrama"
        end
      end
    end
  end
end
