# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nadrama < Formula
  desc "The official CLI for Nadrama.com"
  homepage "https://nadrama.com"
  version "20250905055235"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nadrama-com/homebrew-tap/releases/download/20250905055235/nadrama_darwin_x86_64.tar.gz"
      sha256 "0710225d18208d7bafd4d49a5e7d95806f6f9c133e48475ac62898e6fbae4a72"

      def install
        bin.install "nadrama"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nadrama-com/homebrew-tap/releases/download/20250905055235/nadrama_darwin_arm64.tar.gz"
      sha256 "0e45d15ae0b6c2241062d06a950dd4a458fff1ee9f03857cba2db33081a43c93"

      def install
        bin.install "nadrama"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nadrama-com/homebrew-tap/releases/download/20250905055235/nadrama_linux_x86_64.tar.gz"
        sha256 "49068c5f940510dcf0494c918dce39750cf0c7298e422c7f87f2f1ed8d20907a"

        def install
          bin.install "nadrama"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nadrama-com/homebrew-tap/releases/download/20250905055235/nadrama_linux_arm64.tar.gz"
        sha256 "d04cea16ea3bf9dccd5b3aeccb811a3b9434dcecdad45a4645ff269807edcd3d"

        def install
          bin.install "nadrama"
        end
      end
    end
  end
end
