# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nadrama < Formula
  desc "The official CLI for Nadrama.com"
  homepage "https://nadrama.com"
  version "20250717070931"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nadrama-com/homebrew-tap/releases/download/20250717070931/nadrama_darwin_x86_64.tar.gz"
      sha256 "086ad5f390d64ca4927e916abba703a79773b70f0da03f6da9540652c10579bd"

      def install
        bin.install "nadrama"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nadrama-com/homebrew-tap/releases/download/20250717070931/nadrama_darwin_arm64.tar.gz"
      sha256 "accd1cea02b06ff57e164e22173c2b0157381102a92b170a21cc6074ab835061"

      def install
        bin.install "nadrama"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nadrama-com/homebrew-tap/releases/download/20250717070931/nadrama_linux_x86_64.tar.gz"
        sha256 "4193a6e8e0895bb0b7fc452767b777cefb0153203677d8e3ab984ea882f6d981"

        def install
          bin.install "nadrama"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nadrama-com/homebrew-tap/releases/download/20250717070931/nadrama_linux_arm64.tar.gz"
        sha256 "ee51569ef8d5a6af791b0c8764e0d581c0aac878c27c39913ae6029ad1746ce2"

        def install
          bin.install "nadrama"
        end
      end
    end
  end
end
